### PR TITLE
Reduce scope of middleware exception handling

### PR DESCRIPTION
**Pull request by steventux**
Limit the scope of exception handling to the PDF generation logic in the middleware.

The call to `@app.call(env)` should be able to raise exceptions as these may be legitimate errors from applications or other middlewares.

We noticed that in development mode, our application errors were being obfuscated and caught by the rescue statement for the entire middleware, this appears to be because we also trap errors coming via `@app.call(env)`.

cc @serene - I believe this relates to the review conversation we had here https://github.com/pdfkit/pdfkit/pull/469#pullrequestreview-425899760 please let me know if you need more information.

### CODE REVIEW

**Comment by serene** [comment]
@steventux Test please :)

**Comment by steventux** [comment]
@serene :+1: I've added a test here now https://github.com/pdfkit/pdfkit/pull/476/commits/d60904effce2ceac4f41621aa82763f465b94fa2#diff-115284d51cd4c5774a89ff4272da74a4R410-R418

**Comment by fernandoluizao** [comment]
It would be possible to release a new version with this?

0.8.4.3.1 is catching application exceptions...

**Comment by steventux** [comment]
Hi @serene any news on the next release of pdfkit? Is there likely to be another patch to introduce https://github.com/pdfkit/pdfkit/pull/476/commits/d60904effce2ceac4f41621aa82763f465b94fa2?

**Pull request merged**
