### PR TITLE
Add support for Cover page and TOC

### PR DESCRIPTION
**Pull request by serene**
Attempting to return the quiet flag and fix the broken tests.

### CODE REVIEW

**Comment by serene** [comment]
@sigmavirus24 Any movement on this PR?

**Comment by nicpillinger** [comment]
@sigmavirus24 whats the status on this PR, I could do with this functionality. thanks

**Comment by sigmavirus24** [comment]
@nicpillinger at the earliest it will be in v0.8.0

**Comment by nicpillinger** [comment]
Thanks, happy to help if I can.

**Comment by nicpillinger** [comment]
@serene are you using your branch? if you specify a cover it doesn't seem to support headers/footers correctly. don't pass a cover and the headers and footers re-appear

**Comment by serene** [comment]
@nicpillinger I have not tried out the feature. I just took it over and tried to get it to pass. If you are interested in testing it and fixing the problem, I can add you to the fork

**Pull request closed without merging**
