### PR TITLE
Add Tests, SimpleCov and Fix Repeating Keys Bug

### PR DESCRIPTION
**Pull request by cdwort**
This PR adds test coverage for PDFKit::Configuration and PDFKit::PDFKit#new.

It also fixes a bug related to the handling on string values for repeatable options. 

Previous functionality:

```
$ pdfkit = PDFKit.new('html', allow: "http://google.com")
$ pdfkit.options.include?(['--allow', 'http://google.com'])
=> false
```

New functionality:
```
$ pdfkit = PDFKit.new('html', allow: "http://google.com")
$ pdfkit.options[['--allow', 'http://google.com']]
=> ''
$ pdfkit = PDFKit.new('html', allow: {"http://google.com" => nil, "http://myapp.com" => nil)
$ pdfkit.options[['--allow', 'http://google.com']]
=> ''
```

I believe this is the correct functionality.

### CODE REVIEW

**Comment by cdwort** [comment]
@pdfkit/rb Any thoughts on this? I know it's a lot of tests without much thought put into testing strategy, but I think it gets us closer to the kind of coverage that would allow us to confidently introduce adapters.

There's also the bug fix. Do we want that in a different PR?

I added simplecov and pry as development dependencies, but I'm happy to remove them if anyone objects.

**Comment by cdwort** [comment]
Squashed commits for sanity's sake.

**Comment by sigmavirus24** [comment]
The title seems to imply three separate things are happening in this PR. I haven't reviewed it yet. If that's the case I (personally) would much prefer 3 separate pull requests.

**Comment by cdwort** [comment]
@sigmavirus24 Done. Would love a peer review/thoughts, etc. if you have time.

**Pull request closed without merging**
