### PR TITLE
Tiny cleanups

### PR DESCRIPTION
**Pull request by danbernier**
While working on a PR for a feature request, I made a tiny refactoring, and did some small reformatting.

Separating out here, so it's easier to review.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
What's with the `(m)` in commit messages?

**Comment by danbernier** [comment]
Oh, sorry, it just means "Minor commit." It's a convention at my job, it must've stuck in by habit. I can rebase & reword...?

**Comment by danbernier** [comment]
@sigmavirus24 I reworded them, without the `(m)`. Sorry about that!

**Comment by sigmavirus24** [comment]
Oh you didn't have to go through that trouble @danbernier. I was just curious :smile_cat:

**Comment by danbernier** [comment]
NP, I have fast fingers ;-)

**Comment by sigmavirus24** [comment]
Thanks again @danbernier!

**Comment by danbernier** [comment]
:+1: No problem.

**Pull request merged**
