### PR TITLE
Release 0.7.1

### PR DESCRIPTION
**Pull request by cdwort**
Bump to new version. We've had a lot of changes - let's get them out there.

### CODE REVIEW

**Comment by cdwort** [comment]
@pdfkit/rb Any concerns with this release? I'll push it out at lunch otherwise

**Comment by sigmavirus24** [comment]
Item two on that list sounds like a feature. I would say this is v0.8.0 as a result. Other than that, no concerns. Release numbers are cheap

**Comment by cdwort** [comment]
Yeah, that's fair, except that we should have been supporting those flags already. I'll update to 0.8.0 at lunch unless I hear otherwise.

**Comment by serene** [comment]
I'm good with this release as well.

**Pull request merged**
