### PR TITLE
Require 'uri'

### PR DESCRIPTION
**Pull request by christhekeele**
Closes pdfkit/pdfkit#326.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
:+1: from me. @pdfkit/rb ?

**Comment by cdwort** [comment]
Whoops, that's a miss. :+1: 

I'll release 0.8.2 tonight.

**Comment by christhekeele** [comment]
:+1: Thanks!

**Comment by cdwort** [comment]
Yup, and thank you for the contribution. You'll see your handle in the changelog.

We usually rely on CI to handle the "blank install" issues, but it must not be as clean as I thought since tests were passing without this PR.

**Pull request merged**
