### PR TITLE
Make sure nil values stay as nil: fixes issue with repeatable values

### PR DESCRIPTION
**Pull request by tylerITP**
Fixes issue with repeatable values including '' after each value, this would cause wkhtmltopdf to fail

### CODE REVIEW

**Comment by sigmavirus24** [comment]
> Fixes issue with repeatable values including '' after each value, this would cause wkhtmltopdf to fail

Which issue, is there a bug already filed for this or can you describe it here?

**Comment by tylerITP** [comment]
There wasn't a bug filed. It was an issue I was running into while using 
it. I'll try to explain it here:

The problem appeared when I was trying to use run_script as an option. I 
noticed if I use just one run_script option, then the option wouldn't 
appear at all in the wkhtmltopdf command that was sent. With multiple 
options put in an array like "run_script: [jqueryIncludeScript, 
script]", the wkhtmltopdf command would crash. After debugging it 
appears that the problem was that it would include an extra blank string 
parameter after each key and value pair. E.g. --run-script <script 1> '' 
--run-script <script 2> ''. So what the change I did fixed that, the 
third value now stays nil, by not converting it to a string, and 
therefore won't appear in the command options. So it now outputs as 
--run-script <script 1> --run-script <script 2>

The commit "Fix bug with repeating keys with string values" fixed the 
issue with inputting a single repeatable option but not inputting 
multiple repeatable options.

**Comment by sigmavirus24** [comment]
Would you mind adding tests to this so it doesn't regress?

**Comment by tylerITP** [comment]
Sure, I'll put up some tests by the end of the day

**Comment by tylerITP** [comment]
The tests I just added work with my changes, but fail at the previous commit. So that should be good to go.

**Comment by sigmavirus24** [comment]
LGTM. @pdfkit/rb thoughts?

**Comment by cdwort** [comment]
(thumbsup) Thanks @tylerITP

**Pull request merged**
