### PR TITLE
Wkhtmltopdf 0.12.1

### PR DESCRIPTION
**Pull request by chulkilee**
I'm not sure everything is working well. At least all tests passed.

Related: #200 #234

### CODE REVIEW

**Comment by cdwort** [comment]
@pdfkit/rb The more I get a feel for this project, the more I think this PR should just be merged in. Many, many of our users are on wkHTMLtoPDF 0.12.x and our installation instructions will lead people to end up with such a version. 

We require no code changes to support 0.12.x, so there's really no point in keeping this PR open until a major version change. There's no loss of compatibility. 

Thoughts or concerns?

**Comment by serene** [comment]
I agree. I've been using pdfkit with wkhtmltopdf 0.12.1 for a while in production with no issues. 

Serene



-----Original Message-----

**Comment by sigmavirus24** [comment]
> I agree. I've been using pdfkit with wkhtmltopdf 0.12.1 for a while in production with no issues.

In that case...

**Comment by sigmavirus24** [comment]
:sparkles: :cake: :sparkles:

**Pull request merged**
