### PR TITLE
Add ability to ignore errors

### PR DESCRIPTION
**Pull request by ownadi**

### CODE REVIEW

**Comment by serene** [comment]
@ownadi Would you like to merge in master for this branch?

**Comment by Audiosutras** [comment]
Has this pr been resolved elsewhere?

**Comment by serene** [comment]
@Audiosutras No it has not, but it went stale. If you'd like to pick it up again and merge in master, I'd be happy to review it again.

**Comment by rmmango** [comment]
Is this addressed in any other PR?

**Pull request closed without merging**
